@Library('Jenkins-shared-library') _

pipeline {

  agent any
  stages {
    stage('Call Library with an argument') {
        steps {
            script {
                helloWorld()
            }
        }
    }
  }
}